### ISSUE TITLE
Running the app fails with error

### ISSUE THREAD

**Issue by maxmeyer** [ahhbristow/index_cards#4]
~~~
% docker run -p 4072:4072 --name cards_app --link cards_db:mongo ahhbristow/index_cards
~~~

Results in this error:
~~~
npm info it worked if it ends with ok
npm info using npm@3.3.12
npm info using node@v5.4.0
npm info lifecycle cards_server@0.0.0~prestart: cards_server@0.0.0
npm info lifecycle cards_server@0.0.0~start: cards_server@0.0.0

> cards_server@0.0.0 start /usr/src/app
> node ./bin/www

Loading: development
`open()` is deprecated in mongoose >= 4.11.0, use `openUri()` instead, or set the `useMongoClient` option if using `connect()` or `createConnection()`
Fri, 30 Jun 2017 15:26:49 GMT express-session deprecated undefined resave option; provide resave option at app.js:87:9
Fri, 30 Jun 2017 15:26:49 GMT express-session deprecated undefined saveUninitialized option; provide saveUninitialized option at app.js:87:9
Fri, 30 Jun 2017 15:26:49 GMT express-session deprecated req.secret; provide secret option at app.js:87:9
/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:82
  if (!options.clientID) { throw new TypeError('OAuth2Strategy requires a clientID option'); }
                           ^

TypeError: OAuth2Strategy requires a clientID option
    at Strategy.OAuth2Strategy (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:82:34)
    at new Strategy (/usr/src/app/node_modules/passport-google-oauth20/lib/strategy.js:52:18)
    at module.exports (/usr/src/app/init/google_auth.js:61:15)
    at Object.<anonymous> (/usr/src/app/app.js:95:51)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Module.require (module.js:354:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/src/app/bin/www:7:11)
    at Module._compile (module.js:398:26)
    at Object.Module._extensions..js (module.js:405:10)
    at Module.load (module.js:344:32)
    at Function.Module._load (module.js:301:12)
    at Function.Module.runMain (module.js:430:10)

npm info lifecycle cards_server@0.0.0~start: Failed to exec start script
npm ERR! Linux 4.11.7-1-ARCH
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "start"
npm ERR! node v5.4.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE
npm ERR! cards_server@0.0.0 start: `node ./bin/www`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the cards_server@0.0.0 start script 'node ./bin/www'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the cards_server package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node ./bin/www
npm ERR! You can get their info via:
npm ERR!     npm owner ls cards_server
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /usr/src/app/npm-debug.log
~~~

**Comment by ahhbristow** [comment]
Ah I thought this might happen with the Docker build.  An env_vars folder inside the /config folder needs adding with the correct environment variables that the app can start up with.  I'll get one added ASAP.  Thanks for the feedback!
